### ISSUE TITLE
add entry for gosh newsletter:

### ISSUE THREAD

**Issue by jcolomb** [open-make/open.make-mainrepo#15]
- fair4rh updates, with link to blog
- general updates

https://forum.openhardware.science/t/december-newsletter-call-for-curated-papers-and-projects/3266

**Comment by MoritzMaxeiner** [comment]
I've added you both as Admins on the hackmd note (where I took the above and polished it a little bit): https://hackmd.io/KhXtDJXmTiWHjk_JF5BoeA#
