### ISSUE TITLE
[contact]

### ISSUE THREAD

**Issue by Connectediniot** [open-make/open.make-mainrepo#21]
hello!

I am Ken Li, based in Shenzhen, I got your information from GOSH community, I go to your platform and see you are doing some open hardware, I am interested to engage and support the developing, specially the prototype, mechanical design and manufacturing, thanks!

and I would like to 
- ask you about the projects, are there some hardware projects need to develop and prototyping in Shenzhen?
- propose a collaboration: I can support the supply chain resources.
- ...

Best Regards!
Ken Li
[Connectediniot Brief Oct 2021.pdf](https://github.com/open-make/open.make-mainrepo/files/8109337/Connectediniot.Brief.Oct.2021.pdf)

**Comment by jcolomb** [comment]
We are not doing hardware, thanks

**Comment by Connectediniot** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thanks！！
        
    
        
            
        
    
    
         
        
            font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }font{
            line-height: 1.6;
        }-- Best Regards!李国平 Ken LiWechat: +86.133.2292.4431 (Phone), ***@***.*** Website:www.Connectediniot.comConsultant for your IoT products Design | Manufacture | China Market...地址： 深圳华强北振华路111号中电迪富大厦3楼, 邮编：518031Add:  3F, No.111 Zhenhua Road, Hua Qiang Bei, Shenzhen, Zip code：518031中电智谷国际智能硬件创新示范区CEC i-Valley International Intelligent
Hardware Innovation Park
        
    
     

    On 2/22/2022 16:40，Julien ***@***.***> wrote： 



We are not doing hardware, thanks
