### ISSUE TITLE
prepare PI meeting presentation: 

### ISSUE THREAD

**Issue by jcolomb** [open-make/open.make-mainrepo#23]
from 
https://docs.google.com/document/d/1oog4GIjV1zLPTzLPkeIepjC_UczIbQCtZdTnVthKlww/edit#

to 
https://1drv.ms/u/s!AuvxNTUHju0GgVud3fAWFS6ZVM5E?e=86hIvw

- [x] julien draft
- [x] Robert draft
- [x] Moritz draft
- [x] discussion
- [x] finalisation

**Comment by MoritzMaxeiner** [comment]
I can't seem to add slides there, so I've added the draft for FUB slides (Diana+Me) to the hidrive under `02_Meetings/02_Working meetings/2022-05-13 PI-Meeting`

**Comment by MIE5R0** [comment]
Meeting successfully conducted on 19 Oct. 2022.
