### ISSUE TITLE
adding webhooks for mattermost

### ISSUE THREAD

**Issue by jcolomb** [open-make/open.make-mainrepo#4]
added webhooks on mattermost
trying to set it here
testing now

**Comment by jcolomb** [comment]
not working: https://github.com/open-make/open.make-projmanag/settings/hooks/316965560/deliveries
@MoritzMaxeiner  any clue ?

**Comment by MoritzMaxeiner** [comment]
I've never used these types of webhooks before, sorry to say. I can look into it.

**Comment by jcolomb** [comment]
does it work now ?
